'use strict';

/**
 * Signal Tracker — Paper Trading Outcome Recorder
 *
 * Tracks every signal generated by the ORB strategy and resolves
 * it against live prices as they come in. Persists outcomes to a
 * JSON file so data survives Docker restarts.
 *
 * Resolution rules (mirrors actual Zerodha intraday behaviour):
 *   WIN  — price touches or crosses target before stop-loss
 *   LOSS — price touches or crosses stop-loss before target
 *   EXPIRED — neither hit by 3:15 PM (squared off at close ~ entry price)
 *
 * Per-symbol stats are used by aiAnalyzer.js to produce a
 * data-driven confidence score instead of a random formula.
 */

const fs   = require('fs');
const path = require('path');

// ─── Persistence ──────────────────────────────────────────────────────────────

// Store inside /app/data/ which should be volume-mounted for persistence.
// Falls back to /tmp if the directory doesn't exist yet.
const DATA_DIR  = fs.existsSync('/app/data') ? '/app/data' : path.join(__dirname, '../../data');
const DATA_FILE = path.join(DATA_DIR, 'signal-outcomes.json');

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
}

function loadFromDisk() {
  try {
    ensureDataDir();
    if (!fs.existsSync(DATA_FILE)) return { outcomes: [], symbolStats: {} };
    const raw = fs.readFileSync(DATA_FILE, 'utf8');
    return JSON.parse(raw);
  } catch (_) {
    return { outcomes: [], symbolStats: {} };
  }
}

function saveToDisk() {
  try {
    ensureDataDir();
    fs.writeFileSync(DATA_FILE, JSON.stringify(_store, null, 2), 'utf8');
  } catch (err) {
    console.error(`[SignalTracker] Failed to persist: ${err.message}`);
  }
}

// ─── In-memory store ──────────────────────────────────────────────────────────

const _store = loadFromDisk();

/**
 * Open (unresolved) signals being watched this session.
 * Not persisted — rebuilt on each restart from live prices.
 * @type {Map<string, Object>}
 */
const _open = new Map(); // key: `${symbol}-${signalTimestamp}`

// ─── Helpers ──────────────────────────────────────────────────────────────────

function todayIST() {
  const ist = new Date(Date.now() + 5.5 * 60 * 60 * 1000);
  return ist.toISOString().slice(0, 10);
}

function currentMinsIST() {
  const ist = new Date(Date.now() + 5.5 * 60 * 60 * 1000);
  return ist.getUTCHours() * 60 + ist.getUTCMinutes();
}

/** Rebuild per-symbol stats from the outcomes array. */
function rebuildStats() {
  const stats = {};
  for (const o of _store.outcomes) {
    if (!stats[o.symbol]) stats[o.symbol] = { wins: 0, losses: 0, expired: 0, totalPnl: 0 };
    const s = stats[o.symbol];
    if (o.result === 'WIN')     { s.wins++;    s.totalPnl += o.pnl; }
    if (o.result === 'LOSS')    { s.losses++;  s.totalPnl += o.pnl; }
    if (o.result === 'EXPIRED') { s.expired++; s.totalPnl += o.pnl; }
  }
  _store.symbolStats = stats;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Register a newly generated signal for outcome tracking.
 * Called once per signal from index.js after generateSignals().
 *
 * @param {Object} signal  Full signal object from signalEngine
 */
function trackSignal(signal) {
  const key = `${signal.symbol}-${signal.timestamp || Date.now()}`;
  if (_open.has(key)) return; // already tracking

  _open.set(key, {
    key,
    symbol:     signal.symbol,
    action:     signal.action,
    entry:      parseFloat(signal.entry),
    stopLoss:   parseFloat(signal.stopLoss),
    target:     parseFloat(signal.target),
    positionSize: signal.positionSize || 1,
    score:      signal.score || 60,
    signalAt:   signal.timestamp || new Date().toISOString(),
    date:       todayIST(),
  });

  console.log(`[SignalTracker] 📌 Tracking ${signal.action} ${signal.symbol} — entry ₹${signal.entry} | SL ₹${signal.stopLoss} | target ₹${signal.target}`);
}

/**
 * Feed the latest market prices into the tracker so open signals
 * can be resolved. Call this every pipeline cycle.
 *
 * @param {Array<Object>} stocks  Latest market snapshot
 */
function updatePrices(stocks) {
  if (_open.size === 0) return;

  const priceMap = new Map(stocks.map((s) => [s.symbol, s.price]));
  const nowMins  = currentMinsIST();
  const SQUAREOFF_MINS = 15 * 60 + 15; // 3:15 PM IST

  for (const [key, sig] of _open) {
    const price = priceMap.get(sig.symbol);
    if (price == null) continue;

    let result = null;
    let exitPrice = price;

    if (sig.action === 'BUY') {
      if (price >= sig.target)   { result = 'WIN';  exitPrice = sig.target; }
      if (price <= sig.stopLoss) { result = 'LOSS'; exitPrice = sig.stopLoss; }
    } else {
      if (price <= sig.target)   { result = 'WIN';  exitPrice = sig.target; }
      if (price >= sig.stopLoss) { result = 'LOSS'; exitPrice = sig.stopLoss; }
    }

    // Force-expire at market close
    if (!result && nowMins >= SQUAREOFF_MINS) {
      result    = 'EXPIRED';
      exitPrice = price; // squared off at last traded price
    }

    if (result) {
      const pnl = sig.action === 'BUY'
        ? (exitPrice - sig.entry) * sig.positionSize
        : (sig.entry - exitPrice) * sig.positionSize;

      const outcome = {
        symbol:       sig.symbol,
        action:       sig.action,
        entry:        sig.entry,
        exit:         exitPrice,
        stopLoss:     sig.stopLoss,
        target:       sig.target,
        positionSize: sig.positionSize,
        result,
        pnl:          parseFloat(pnl.toFixed(2)),
        signalAt:     sig.signalAt,
        resolvedAt:   new Date().toISOString(),
        date:         sig.date,
      };

      _store.outcomes.push(outcome);
      _open.delete(key);

      const icon = result === 'WIN' ? '✅' : result === 'LOSS' ? '❌' : '⏱';
      console.log(`[SignalTracker] ${icon} ${result} | ${sig.symbol} ${sig.action} | exit ₹${exitPrice.toFixed(2)} | P&L ₹${pnl.toFixed(2)}`);

      // Rebuild stats and persist after each resolution
      rebuildStats();
      saveToDisk();
    }
  }
}

/**
 * Get per-symbol win rate stats.
 * @param {string} symbol
 * @returns {{ winRate: number, trades: number, wins: number, losses: number, totalPnl: number }}
 */
function getSymbolStats(symbol) {
  const s = _store.symbolStats[symbol];
  if (!s) return { winRate: null, trades: 0, wins: 0, losses: 0, expired: 0, totalPnl: 0 };
  const decided = s.wins + s.losses; // expired = inconclusive, not counted in WR
  return {
    winRate:  decided > 0 ? s.wins / decided : null,
    trades:   s.wins + s.losses + s.expired,
    wins:     s.wins,
    losses:   s.losses,
    expired:  s.expired,
    totalPnl: s.totalPnl,
  };
}

/**
 * Get overall portfolio stats (all symbols combined).
 * @returns {Object}
 */
function getPortfolioStats() {
  let wins = 0, losses = 0, expired = 0, totalPnl = 0;
  for (const o of _store.outcomes) {
    if (o.result === 'WIN')     { wins++;    totalPnl += o.pnl; }
    if (o.result === 'LOSS')    { losses++;  totalPnl += o.pnl; }
    if (o.result === 'EXPIRED') { expired++; totalPnl += o.pnl; }
  }
  const decided = wins + losses;
  const winRate  = decided > 0 ? wins / decided : null;

  // Profit factor = gross profit / gross loss
  const grossProfit = _store.outcomes.filter((o) => o.pnl > 0).reduce((a, o) => a + o.pnl, 0);
  const grossLoss   = Math.abs(_store.outcomes.filter((o) => o.pnl < 0).reduce((a, o) => a + o.pnl, 0));
  const profitFactor = grossLoss > 0 ? parseFloat((grossProfit / grossLoss).toFixed(2)) : null;

  // Max drawdown (running P&L low watermark)
  let peak = 0, runningPnl = 0, maxDD = 0;
  for (const o of _store.outcomes) {
    runningPnl += o.pnl;
    if (runningPnl > peak) peak = runningPnl;
    const dd = peak - runningPnl;
    if (dd > maxDD) maxDD = dd;
  }

  // Symbol breakdown
  const bySymbol = {};
  for (const [sym, s] of Object.entries(_store.symbolStats)) {
    const d = s.wins + s.losses;
    bySymbol[sym] = {
      wins: s.wins, losses: s.losses, expired: s.expired,
      winRate: d > 0 ? parseFloat((s.wins / d * 100).toFixed(1)) : null,
      totalPnl: parseFloat(s.totalPnl.toFixed(2)),
    };
  }

  return {
    totalTrades:  wins + losses + expired,
    wins,
    losses,
    expired,
    winRate:      winRate != null ? parseFloat((winRate * 100).toFixed(1)) : null,
    totalPnl:     parseFloat(totalPnl.toFixed(2)),
    profitFactor,
    maxDrawdown:  parseFloat(maxDD.toFixed(2)),
    bySymbol,
    recentTrades: _store.outcomes.slice(-20).reverse(),
  };
}

/**
 * Get the last N resolved outcomes (newest first).
 * Used by the confidence scorer to detect recent strategy drift.
 * @param {number} n
 * @returns {Array<Object>}
 */
function getRecentOutcomes(n = 10) {
  return _store.outcomes.slice(-n).reverse();
}

/**
 * Count of signals currently being tracked (not yet resolved).
 */
function getOpenCount() {
  return _open.size;
}

module.exports = {
  trackSignal,
  updatePrices,
  getSymbolStats,
  getPortfolioStats,
  getRecentOutcomes,
  getOpenCount,
};
